name: mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../common
  theme:
    path: ../theme

  # UI
  flutter_floating_bottom_bar: ^1.2.0
  cupertino_icons: ^1.0.2

  # Navigator
  go_router: ^11.1.2

  # State
  riverpod_generator: ^2.3.3
  flutter_riverpod: ^2.4.2
  riverpod_annotation: ^2.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router_builder: ^2.3.3
  riverpod_lint: ^2.2.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
